export const headerBanners = [
  {
    id: '1',
    image: 'https://lh7-us.googleusercontent.com/docsz/AD_4nXeJ5eONXRQJnsej2yIbVHnfZLB8tAR003qnhuwhAavkP6U7XuqNxrfc6Hadw4d8QKCs79wC8JyucbJVy374NokwUybd_JX5FfDzJp578sYysrITiAxS5aPvSlrUzwAbkV9ghwR0PQLpy3PdTvOc05zyfSYo?key=rWSGy3whMcjyqwOBdaWRgA',
  },
  {
    id: '2',
    image: 'https://static.vecteezy.com/system/resources/previews/025/006/067/non_2x/colorful-summer-background-layout-banners-design-template-3d-product-display-cylindrical-shape-horizontal-poster-greeting-card-header-website-sale-ad-promotion-vector.jpg',
  },
  {
    id: '3',
    image: 'https://m.media-amazon.com/images/I/01UwfHrld%2BL._TSa%7Csize%3A1910%2C1000%7Cformat%3A%28A%2Cf%2Cb%2Cd%2Cpi%2Cpl%2Co%29%7Cb-src%3A61Cd2rJZgRL.png%7Cb-pos%3A0%2C0%2C1910%2C1000%7Cpi-src%3A51kmOex1dvL.jpg%7Cpi-pos%3A1000%2C100%2C840%2C840.json',
  },
  {
    id: '4',
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f',
  },
  {
    id: '5',
    image: 'https://images.unsplash.com/photo-1521334884684-d80222895322',
  },
];

export const categories = [
  { id: '0', title: 'All', icon: '...' },
  { id: '1', title: 'Electronics', icon: '💻' },
  { id: '2', title: 'Clothes', icon: '👕' },
  { id: '3', title: 'Toys', icon: '🧸' },
  { id: '4', title: 'Sports', icon: '🏀' }, 
  { id: '5', title: 'Shoes', icon: '👟' },
  { id: '6', title: 'Beauty', icon: '💄' },
  { id: '7', title: 'Groceries', icon: '🛒' },
  { id: '8', title: 'Furniture', icon: '🛋️' },
  { id: '9', title: 'Books', icon: '📚' },
  { id: '10', title: 'Kids', icon: '👶' },
  { id: '11', title: 'Fitness', icon: '🏋️' },
  { id: '12', title: 'Gaming', icon: '🎮' },
  { id: '13', title: 'Travel', icon: '✈️' },
  { id: '14', title: 'Automotive', icon: '🚗' },
  { id: '15', title: 'Jewelry', icon: '💍' },
  { id: '16', title: 'Pets', icon: '🐶' },
  { id: '17', title: 'Garden', icon: '🌿' },
  { id: '18', title: 'Music', icon: '🎵' },
  { id: '19', title: 'Office', icon: '🖨️' },
  { id: '20', title: 'Health', icon: '🩺' },
];

export const topPicks = [
  {
    id: '1',
    name: 'Amazon',
    logo: 'https://1000logos.net/wp-content/uploads/2016/10/Amazon-Logo-tumb.png',
  },
  {
    id: '2',
    name: 'Nike',
    logo: 'https://1000logos.net/wp-content/uploads/2021/11/Nike-Logo-tumb.jpg',
  },
  {
    id: '3',
    name: 'Apple',
    logo: 'https://1000logos.net/wp-content/uploads/2019/06/Apple-Logo.jpg',
  },
  {
    id: '4',
    name: 'BMW',
    logo: 'https://1000logos.net/wp-content/uploads/2018/02/BMW-Logo-500x281-1.jpg',
  },
  {
    id: '5',
    name: 'Ferrari',
    logo: 'https://1000logos.net/wp-content/uploads/2018/02/Ferrari-logo-tumb.jpg',
  },
  {
    id: '6',
    name: 'MBL Teams',
    logo: 'https://1000logos.net/wp-content/uploads/2025/06/MLB-Teams-Logo.png',
  },
  {
    id: '7',
    name: 'WNBA Teams',
    logo: 'https://1000logos.net/wp-content/uploads/2025/06/WNBA-Teams-Logo.png',
  },
  {
    id: '8',
    name: 'Starbucks',
    logo: 'https://1000logos.net/wp-content/uploads/2016/12/Starbucks-logo-tumb.jpg',
  },

];

export const CouponItems_List = [
   {
    id: 'c1',
    title: 'MacBook Pro M2',
    brand: 'Amazon',
    discount: 15,
    category: 'Electronics',
    description: 'Save big on the powerful MacBook Pro M2 with limited-time Amazon deals.',
    couponCode: 'AMZ-MBP15',
    validUntil: '2025-01-31',
    reviews: 124,
    rating: 4.6,
    isFeatured: true,
    isFavorites: true,
    isUtilized: false,
    images: [
      { id: 0, image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80' },
      { id: 1, image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80' },
      { id: 2, image: 'https://images.unsplash.com/photo-1518779578993-ec3579fee39f?auto=format&fit=crop&w=800&q=80' },
    ],
  },

  {
    id: 'c2',
    title: 'Nike Running Shoes',
    brand: 'Nike',
    discount: 30,
    category: 'Sports',
    description: 'High-performance Nike running shoes with breathable comfort.',
    couponCode: 'NIKE30',
    validUntil: '2024-12-20',
    reviews: 89,
    rating: 4.4,
    isFeatured: true,
    isFavorites: false,
    isUtilized: false,
    images: [
      { id: 0, image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80' },
      { id: 1, image: 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=800&q=80' },
    ],
  },

  {
    id: 'c3',
    title: 'iPhone 15 Pro',
    brand: 'Apple',
    discount: 10,
    category: 'Mobiles',
    description: 'Experience the latest iPhone with titanium design and pro camera.',
    couponCode: 'APL-IP15',
    validUntil: '2025-02-15',
    reviews: 210,
    rating: 4.8,
    isFeatured: true,
    isFavorites: false,
    isUtilized: false,
    images: [
      { id: 0, image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80' },
      { id: 1, image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80' },
    ],
  },

  {
    id: 'c4',
    title: 'Sony Headphones',
    brand: 'Sony',
    discount: 25,
    category: 'Audio',
    description: 'Noise-canceling wireless headphones with premium sound.',
    couponCode: 'SONY25',
    validUntil: '2024-11-30',
    reviews: 76,
    rating: 4.5,
    isFeatured: true,
    isFavorites: true,
    isUtilized: false,
    images: [
      { id: 0, image: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?auto=format&fit=crop&w=800&q=80' },
      { id: 1, image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=800&q=80' },
    ],
  },

  {
    id: 'c5',
    title: 'Smart Watch',
    brand: 'Samsung',
    discount: 20,
    category: 'Wearables',
    description: 'Track your fitness and health with the latest Samsung smartwatch.',
    couponCode: 'SMRT20',
    validUntil: '2025-03-10',
    reviews: 132,
    rating: 4.3,
    isFeatured: false,
    isFavorites: false,
    isUtilized: false,
    images: [
      { id: 0, image: 'https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?auto=format&fit=crop&w=800&q=80' },
    ],
  },

  {
    id: 'c6',
    title: 'Gaming Laptop',
    brand: 'ASUS',
    discount: 18,
    category: 'Gaming',
    description: 'High-end gaming laptop with RTX graphics.',
    couponCode: 'GAME18',
    validUntil: '2025-04-01',
    reviews: 64,
    rating: 4.7,
    isFeatured: true,
    isFavorites: false,
    isUtilized: false,
    images: [
      { id: 0, image: 'https://images.unsplash.com/photo-1611078489935-0cb964de46d6?auto=format&fit=crop&w=800&q=80' },
    ],
  },

  {
    id: 'c7',
    title: 'DSLR Camera',
    brand: 'Canon',
    discount: 22,
    category: 'Photography',
    description: 'Capture stunning photos with Canon professional DSLR.',
    couponCode: 'CANON22',
    validUntil: '2025-01-15',
    reviews: 98,
    rating: 4.6,
    isFeatured: false,
    isFavorites: true,
    isUtilized: false,
    images: [
      { id: 0, image: 'https://d25thuhsbcr6yb.cloudfront.net/m/s/28889/28879096/a-0072.png' },
    ],
  },

  {
    id: 'c8',
    title: 'Leather Jacket',
    brand: 'Zara',
    discount: 35,
    category: 'Fashion',
    description: 'Premium leather jacket with modern fit.',
    couponCode: 'ZARA35',
    validUntil: '2024-12-05',
    reviews: 54,
    rating: 4.2,
    isFeatured: false,
    isFavorites: false,
    isUtilized: false,
    images: [
      { id: 0, image: 'https://images.unsplash.com/photo-1520975916090-3105956dac38?auto=format&fit=crop&w=800&q=80' },
    ],
  },

  {
    id: 'c9',
    title: 'Office Chair',
    brand: 'IKEA',
    discount: 40,
    category: 'Furniture',
    description: 'Ergonomic office chair for long working hours.',
    couponCode: 'IKEA40',
    validUntil: '2025-02-01',
    reviews: 142,
    rating: 4.4,
    isFeatured: true,
    isFavorites: false,
    isUtilized: false,
    images: [
      { id: 0, image: 'https://d25thuhsbcr6yb.cloudfront.net/m/s/28889/28879096/a-0072.png' },
    ],
  },

  {
    id: 'c10',
    title: 'Air Fryer',
    brand: 'Philips',
    discount: 28,
    category: 'Kitchen',
    description: 'Healthy cooking with less oil using Philips Air Fryer.',
    couponCode: 'FRY28',
    validUntil: '2025-03-20',
    reviews: 180,
    rating: 4.5,
    isFeatured: false,
    isFavorites: false,
    isUtilized: false,
    images: [
      { id: 0, image: 'https://d25thuhsbcr6yb.cloudfront.net/m/s/28889/28879096/a-0072.png' },
    ],
  },
]
