export const favoriteCoupons = [
  {
    id: 'c1',
    title: 'MacBook Pro M2',
    brand: 'Amazon',
    discount: 15,
    category: 'Electronics',
    description: 'Exclusive discount on MacBook Pro M2.',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8',
    couponCode: 'AMZ-MBP15',
    validUntil: '2025-01-31',
    reviews: 124,
    rating: 4.6,
    isFeatured: 1,
    isFavorites: 1,
    isUtilized: 0,
  },
  {
    id: 'c5',
    title: 'Smart Watch Series 7',
    brand: 'Apple',
    discount: 10,
    category: 'Electronics',
    description: 'Track your health and notifications.',
    image: 'https://images.unsplash.com/photo-1611162617218-82d79d3bbfa7',
    couponCode: 'APL-WATCH10',
    validUntil: '2025-01-20',
    reviews: 140,
    rating: 4.7,
    isFeatured: 1,
    isFavorites: 1,
    isUtilized: 0,
  },
];
